### ISSUE TITLE
The averaging in fictitious play is not correct.

### ISSUE THREAD

**Issue by abhishm** [oyamad/fictplay#1]
In line 74 where we are updating the belief for each player, we should replace (t+2) by (t+1). 

Precisely, 

```
    self.current_beliefs = [
        self.current_beliefs[player] +
        (1/(t+2)) * (self.mixed_actions[1-player] - self.current_beliefs[player])
        for player in self.players
        ]
```

should be replaced by

```
    self.current_beliefs = [
        self.current_beliefs[player] +
        (1/(t+1)) * (self.mixed_actions[1-player] - self.current_beliefs[player])
        for player in self.players
        ]
```

Please let me know your opinion.

Thank you

**Comment by oyamad** [comment]
@abhishm Thank you for your interest in this repo.

Actually this is how it is designed: the implementation here is that the initial beliefs (not actions) are given at time `0`.

Let `x_0(t)` be the belief of player `0` at time `t` for player `1`'s actions.
1. Initial belief `x_0(0)` is randomly assigned.
2. If `a_1(0), ..., a_1(t-1)` are player `1`'s (mixed) actions, then player `0`'s belief at time `t` is given by
   `x_0(t) = [x_0(0) + a_1(0) + ... + a_1(t-1)] / (t+1)`.
3. Then in a recursive form,
   `x_0(t+1) = [x_0(0) + a_1(0) + ... + a_1(t)] / (t+2) = x_0(t) + [1/(t+2)] (a_1(t) - x_0(t))`.

The content of this project has been merged in the [game_theory_models](https://github.com/oyamad/game_theory_models) repo. I plan to refactor the code there to submit to [QuantEcon.py](https://github.com/QuantEcon/QuantEcon.py) (sometime in the near future).

**Comment by abhishm** [comment]
@oyamad Thank you very much your explanation. I realize it was a mistake on my part.
